rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::TestInfantry -> lift_test_infantry
      - rmcs_core::controller::chassis::ChassisLiftController -> lift_test
      #- rmcs_core::controller::adrc -> lift_adrc_test
lift_test_infantry:
  ros__parameters:
    usb_pid: -1

lift_test:
  ros__parameters:
    Initial_length: 56.64
    Rod_relative_horizontal_coordinate: -9.5
    Rod_relative_longitudinal_coordinate: 90.0
    Rod_length: 100.0
    Load: 16.06153


#An example
# lift_adrc_test:
#   ros__parameters:
#     measurement: /chassis/lift/left_front_wheel/encoder_angle
#     target: /chassis/lift/target_angle
#     control: /chassis/lift/left_front_wheel/control_torque
#     kt: 1.0 #转矩参数
#     wc: 5.0 #w_c * w_c w_c为控制器带宽
#     b0: 1.0
#     w0: 167.0 #w_0为观测器带宽
#     alpha1: 0.5
#     alpha2: 0.2
#     delta: 0.01 #5~10 * 0.001
#     kp: 5.0 #w_c
#     kd: 2.5 #w_c/2
#     output_max: 114514.0
#     output_min: -114514.0