rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::TestInfantry -> lift_test_infantry
      - rmcs_core::controller::chassis::ChassisLiftController -> lift_test
      - rmcs_core::controller::smc::SlidingModeController -> smc_controller
      - rmcs_core::controller::smc::GimbalObserver -> GimbalObserver
      - rmcs_core::broadcaster::ValueBroadcaster -> broadcaster

lift_test_infantry:
  ros__parameters:
    usb_pid: -1

lift_test:
  ros__parameters:
    Initial_length: 56.64
    Rod_relative_horizontal_coordinate: -9.5
    Rod_relative_longitudinal_coordinate: 90.0
    Rod_length: 100.0

smc_controller:
  ros__parameters:
    c: 1.0
    epsilon: 0.3
    k: 5.0
    phi: 0.001
    J: 0.05
    B: 0.3
    gear_ratio: 25.0
    angle_error: /chassis/lift/lf/control_angle_error
    current_velocity: /chassis/lift/left_front_wheel/velocity
    target_velocity: /chassis/lift/left_front_wheel/expect_velocity
    target_acceleration: /chassis/lift/left_front_wheel/expect_acceleration
    control_torque: /chassis/lift/left_front_wheel/control_torque

GimbalObserver:
  ros__parameters:
    velocity_limit: 10.0
    acceleration_limit: 10.0

broadcaster:
  ros__parameters:  
    forward_list:
      - /smc/s_value
      - /chassis/lift/left_front_wheel/expect_velocity
      - /chassis/lift/left_front_wheel/expect_acceleration
      - /chassis/lift/left_front_wheel/velocity
      - /chassis/lift/left_front_wheel/control_torque
      - /chassis/lift/lf/control_angle_error
      