rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::TestInfantry -> lift_test_infantry
      - rmcs_core::controller::chassis::ChassisLiftController -> lift_test

lift_test_infantry:
  ros__parameters:
    usb_pid: -1

lift_test:
  ros__parameters:
    L0: 10
    Bx: 9.5
    By: 90
    L: 100
