rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::TestInfantry -> lift_test_infantry
      - rmcs_core::controller::chassis::ChassisLiftController -> lift_test

lift_test_infantry:
  ros__parameters:
    usb_pid: -1

lift_test:
  ros__parameters:
    min_angle: 0.436332
    max_angle: 1.308997